spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/likelion_spring_boot_jpa_test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:./likelion_spring_boot_jpa_test;MODE=MySQL
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: create